# Generated by Django 5.2.6 on 2025-09-21 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_bank', models.IntegerField()),
                ('to_bank', models.IntegerField()),
                ('amount_received', models.FloatField()),
                ('receiving_currency', models.CharField(max_length=100)),
                ('amount_paid', models.FloatField()),
                ('payment_currency', models.CharField(max_length=100)),
                ('payment_format', models.CharField(max_length=50)),
                ('probability', models.FloatField()),
                ('prediction', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
